const state={folder:'',media:null,targets:new Set(['en']),languages:{},jobs:[]};
const $=id=>document.getElementById(id);
async function api(url,options){const response=await fetch(url,options);let data;try{data=await response.json()}catch{throw Error(`Request failed (${response.status})`)}if(!response.ok)throw Error(data.error||`Request failed (${response.status})`);return data}
function element(tag,className,text){const item=document.createElement(tag);if(className)item.className=className;if(text!==undefined)item.textContent=text;return item}
function seconds(value){if(!value)return 'Duration unknown';let total=Math.round(value);return `${Math.floor(total/3600)}:${String(Math.floor(total%3600/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function displayError(message){$('form-error').textContent=message;$('form-error').hidden=!message}
async function loadConfig(){const data=await api('/api/config');state.languages=data.languages;$('whisper-model').textContent=`Whisper ${data.whisper_model}`;const source=$('source-language');source.append(new Option('Auto detect','auto'));for(const [code,name] of Object.entries(data.languages))source.append(new Option(`${name} (${code})`,code));const choices=$('language-grid');for(const [code,name] of Object.entries(data.languages)){const button=element('button','lang-button',`${name} · ${code.toUpperCase()}`);button.type='button';button.dataset.code=code;button.onclick=()=>{state.targets.has(code)?state.targets.delete(code):state.targets.add(code);button.classList.toggle('selected',state.targets.has(code))};button.classList.toggle('selected',state.targets.has(code));choices.append(button)}const models=$('model-select');if(data.models.length){for(const model of data.models)models.append(new Option(model,model));models.value=data.default_model||data.models[0];$('model-note').textContent='Models available through your local LM Studio server.'}else{models.append(new Option('No model available',''));$('model-note').textContent=data.model_error?`LM Studio is unavailable: ${data.model_error}`:'Load a model in LM Studio to enable translations.'}models.disabled=!data.models.length}
function showBreadcrumb(path){const bar=$('breadcrumb');bar.replaceChildren();const parts=path?path.split('/'):[];const root=element('button','', 'Library');root.onclick=()=>loadFolder('');bar.append(root);parts.forEach((part,index)=>{bar.append(element('span','', '›'));const button=element('button','',part);button.onclick=()=>loadFolder(parts.slice(0,index+1).join('/'));bar.append(button)})}
async function loadFolder(path){const list=$('library-list');list.replaceChildren(element('div','empty','Loading folder…'));try{const data=await api(`/api/library?path=${encodeURIComponent(path)}`);state.folder=data.path;showBreadcrumb(data.path);list.replaceChildren();if(!data.entries.length)list.append(element('div','empty','No media files in this folder.'));for(const entry of data.entries){const button=element('button','library-item');button.type='button';button.classList.toggle('selected',entry.path===state.media?.path);button.append(element('span','symbol',entry.type==='folder'?'▰':'▶'),element('span','name',entry.name));if(entry.type==='folder')button.append(element('span','chevron','›'));button.onclick=()=>entry.type==='folder'?loadFolder(entry.path):selectMedia(entry.path);list.append(button)}}catch(error){list.replaceChildren(element('div','empty',error.message))}}
async function selectMedia(path){displayError('');try{const media=await api(`/api/media?path=${encodeURIComponent(path)}`);if(!media.tracks.length)throw Error('This file has no audio tracks');state.media=media;$('media-empty').hidden=true;$('media-options').hidden=false;$('media-name').textContent=path.split('/').at(-1);$('media-duration').textContent=seconds(media.duration);const tracks=$('audio-track');tracks.replaceChildren();for(const track of media.tracks){let label=`Track ${track.index} · ${track.language.toUpperCase()} · ${track.codec}`;if(track.title)label+=` · ${track.title}`;if(track.channels)label+=` · ${track.channels} ch`;tracks.append(new Option(label,String(track.index)))}loadFolder(state.folder)}catch(error){displayError(error.message)}}
async function submitJob(){displayError('');if(!state.media)return displayError('Choose a video first.');if(!state.targets.size&&!$('transcript').checked)return displayError('Select an output language or save the transcript.');const model=$('model-select').value;if(state.targets.size&&!model)return displayError('Load a translation model in LM Studio first.');const button=$('submit-job');button.disabled=true;try{await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:state.media.path,audio_stream_index:Number($('audio-track').value),source_language:$('source-language').value,transcript:$('transcript').checked,targets:[...state.targets],model})});await loadJobs()}catch(error){displayError(error.message)}finally{button.disabled=false}}
async function loadJobs(){try{state.jobs=await api('/api/jobs');const list=$('jobs-list');list.replaceChildren();if(!state.jobs.length){list.append(element('div','empty','No jobs yet.'));return}for(const job of state.jobs){const card=element('div','job');const top=element('div','job-top');top.append(element('div','job-name',job.filename),element('span',`badge ${job.status}`,job.status));card.append(top);let stage=job.stage;if(job.status==='running'&&job.stage==='Transcribing'&&job.duration)stage+=` · ${seconds(job.position)} / ${seconds(job.duration)}`;card.append(element('div','job-stage',`${stage} · ${job.progress}%`));const progress=element('div','progress');const fill=element('div');fill.style.width=`${job.progress}%`;progress.append(fill);card.append(progress);if(job.error)card.append(element('div','job-error',job.error));const codes=Object.keys(job.outputs||{});if(codes.length){const links=element('div','downloads');for(const code of codes){const link=element('a','',`${code.toUpperCase()} .srt ↓`);link.href=job.outputs[code].url;links.append(link)}card.append(links)}list.append(card)}}catch(error){$('jobs-list').replaceChildren(element('div','empty',error.message))}}
$('refresh-library').onclick=()=>loadFolder(state.folder);$('refresh-jobs').onclick=loadJobs;$('submit-job').onclick=submitJob;Promise.all([loadConfig(),loadFolder(''),loadJobs()]).catch(error=>displayError(error.message));setInterval(loadJobs,2500);
